CREATE TABLE "researgence" (
	"pub_id" integer PRIMARY KEY NOT NULL,
	"authors" text,
	"home_authors" text,
	"home_author_department" text,
	"home_author_institute" text,
	"publication_title" text,
	"scs" integer,
	"wos" integer,
	"sci" text,
	"source_publication" text,
	"level" text,
	"article_type" text,
	"year" integer,
	"month" text,
	"home_author_location" text,
	"vol_no" text,
	"iss_no" text,
	"b_page" text,
	"e_page" text,
	"snip" numeric,
	"sjr" numeric,
	"if" numeric,
	"cite_score" numeric,
	"q_rank_scs" text,
	"q_rank_wos" text,
	"p_issn" text,
	"e_issn" text,
	"p_isbn" text,
	"e_isbn" text,
	"link" text
);
--> statement-breakpoint
CREATE INDEX "title_idx" ON "researgence" USING btree ("publication_title");